repos:
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
            language_version: python3.7
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
          - id: flake8
    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.0
      hooks:
        - id: nbstripout
